AWSTemplateFormatVersion: 2010-09-09

Description: 'The AWS CloudFormation template creates KMS encryption keys for CloudTrail and S3, an encrypted S3 bucket, and enables CloudTrail for the account'

Resources:
    # Create S3 bucket for log storage
    CloudTrailS3Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          IgnorePublicAcls: true
          BlockPublicPolicy: true
          RestrictPublicBuckets: true
        VersioningConfiguration:
          Status: Enabled

    CloudTrailBucketPolicy:
      DependsOn:
          - CloudTrailS3Bucket
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref CloudTrailS3Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "AWSCloudTrailAclCheck"
              Effect: Allow
              Principal:
                Service: 'cloudtrail.amazonaws.com'
              Action: "s3:GetBucketAcl"
              Resource: !Sub arn:aws:s3:::${CloudTrailS3Bucket}
            - Sid: "AWSCloudTrailWrite"
              Effect: Allow
              Principal:
                Service: 'cloudtrail.amazonaws.com'
              Action: "s3:PutObject"
              Resource: !Sub arn:aws:s3:::${CloudTrailS3Bucket}/AWSLogs/${AWS::AccountId}/*
              Condition:
                StringEquals:
                  's3:x-amz-acl': 'bucket-owner-full-control'

    # Create IAM user and permission to access S3
    MyIAMUser:
      Type: AWS::IAM::User
      Properties:
        UserName: s3-access-user

    MyIAMUserPolicy:
      Type: AWS::IAM::Policy
      DependsOn: CloudTrailS3Bucket
      Properties:
        PolicyName: my-s3-access-policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetObject
              Resource: 
                - !Sub arn:aws:s3:::${CloudTrailS3Bucket}
        Users:
          - !Ref MyIAMUser


    # Enable CloudTrail
    MyCloudTrail:
      DependsOn:
        - CloudTrailS3Bucket
        - CloudTrailBucketPolicy
      Type: AWS::CloudTrail::Trail
      Properties:
        S3BucketName: !Ref CloudTrailS3Bucket
        IsLogging: true

