AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template to create a trail that specifies the settings for delivery of log data to a S3 bucket "


Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: rapid7  

  # Create CloudTrail encrypted S3 bucket for storage
  CloudTrailS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rapid7-trail-logs
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck20150319
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: !Sub "arn:aws:s3:::${CloudTrailS3Bucket}"
          - Sid: AWSCloudTrailWrite20150319
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${CloudTrailS3Bucket}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          - Sid: AllowIAMUserAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/${rapid7}"
            Action:
              - "s3:List*"
              - "s3:GetObject"
            Resource:
              - !Sub "arn:aws:s3:::${CloudTrailS3Bucket}"
              - !Sub "arn:aws:s3:::${CloudTrailS3Bucket}/*"

  MyIAMUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3AccessPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowS3Access
            Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
            Resource:
              - !GetAtt CloudTrailS3Bucket.Arn
              - !Sub "${CloudTrailS3Bucket.Arn}/*"
      Users:
        - !Ref MyIAMUser

  Trail:
    DependsOn:
      - CloudTrailS3Bucket
    Type: AWS::CloudTrail::Trail
    Properties:   
      TrailName: Rapid-7
      # S3BucketName: rapid7-trail-logs
      S3BucketName: !Ref CloudTrailS3Bucket
      IsLogging: True
      EventSelectors:
        - IncludeManagementEvents: true
          ReadWriteType: All
      


