AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template to create an S3 bucket"

Parameters:
  BucketName:
    Description: "Cloudtrail-rapid7"
    Type: String

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref BucketName
      Region: "us-east-1"

Output:
  S3Bucket:
    Description: S3 bucket created from a Cloudformation Template
    Value: !Ref S3Bucket

  